/^BIT_initDStream$/d
/^F2FS_SUPER_BLOCK$/d
/^FSE_initDState$/d
/^HAS_UNMAPPED_ID$/d
/^HUF_compressCTable_internal$/d
/^ZSTD_deriveSeqStoreChunk$/d
/^ZSTD_estimateCCtxSize_usingCCtxParams_internal$/d
/^ZSTD_initFseState$/d
/^ZSTD_safecopyDstBeforeSrc$/d
/^___bpf_copy_key$/d
/^___d_drop$/d
/^___sys_recvmsg$/d
/^___sys_sendmsg$/d
/^__add_partial$/d
/^__addr_hash$/d
/^__address_space_init_once\.__key$/d
/^__arm_v7s_free_table$/d
/^__arpt_unregister_table$/d
/^__bpf_lru_node_move$/d
/^__bpf_map_offload_destroy$/d
/^__bpf_prog_run_save_cb$/d
/^__br_handle_local_finish$/d
/^__br_multicast_get_querier_port$/d
/^__btf_name_valid$/d
/^__check_buffer_access$/d
/^__clear_user$/d
/^__copy_from_user_inatomic_nocache$/d
/^__create_val_field$/d
/^__d_instantiate$/d
/^__device_link_del$/d
/^__device_links_no_driver$/d
/^__device_links_queue_sync_state$/d
/^__disable_kprobe$/d
/^__dl_add$/d
/^__dl_sub$/d
/^__do_loopback$/d
/^__dquot_drop$/d
/^__dtpm_add_power$/d
/^__dump_skip$/d
/^__ecc_is_key_valid$/d
/^__ethtool_get_sset_count$/d
/^__ethtool_set_flags$/d
/^__f2fs_cluster_blocks$/d
/^__f2fs_setup_filename$/d
/^__fanout_link$/d
/^__fanout_set_data_bpf$/d
/^__ffs_data_do_entity$/d
/^__ffs_event_add$/d
/^__ffs_func_bind_do_nums$/d
/^__fib6_drop_pcpu_from$/d
/^__find_governor$/d
/^__find_snapshots_sharing_cow$/d
/^__folio_put_large$/d
/^__fpr_set$/d
/^__fpsimd_to_sve$/d
/^__free_rcu$/d
/^__freelist_add$/d
/^__func_get_name$/d
/^__fw_state_set$/d
/^__get_obj_cgroup_from_memcg$/d
/^__get_segment_type$/d
/^__gre_xmit$/d
/^__hw_addr_unsync_one$/d
/^__hyp_pgtable_moveable_regs_pages$/d
/^__init_nat_entry$/d
/^__insert_pending_exception$/d
/^__insert_snapshot$/d
/^__invalidate_bh_lrus$/d
/^__invalidate_snapshot$/d
/^__io_flush_post_cqes$/d
/^__io_openat_prep$/d
/^__iommu_device_set_domain$/d
/^__iommu_map$/d
/^__ip6_del_rt$/d
/^__ipv4_neigh_lookup_noref$/d
/^__ipv6_addr_label$/d
/^__ipv6_neigh_lookup_noref_stub$/d
/^__is_kfunc_ptr_arg_type$/d
/^__is_ram$/d
/^__key_get$/d
/^__kvm_io_bus_write$/d
/^__kvm_nvhe___check_host_unshare_guest_order$/d
/^__kvm_nvhe___copy_vcpu_state$/d
/^__kvm_nvhe___guest_check_page_state_range$/d
/^__kvm_nvhe___guest_initiate_page_transition$/d
/^__kvm_nvhe___host_check_page_state_range$/d
/^__kvm_nvhe___host_set_page_state_range$/d
/^__kvm_nvhe___hyp_check_page_state_range$/d
/^__kvm_nvhe___unmap_donated_memory$/d
/^__kvm_nvhe_chunk_inc_map$/d
/^__kvm_nvhe_chunk_merge$/d
/^__kvm_nvhe_ffa_call_supported$/d
/^__kvm_nvhe_ffa_host_share_ranges$/d
/^__kvm_nvhe_ffa_host_unshare_ranges$/d
/^__kvm_nvhe_ffa_mem_reclaim$/d
/^__kvm_nvhe_ffa_rx_release$/d
/^__kvm_nvhe_ffa_unmap_hyp_buffers$/d
/^__kvm_nvhe_hyp_allocator_unmap$/d
/^__kvm_nvhe_pkvm_handle_empty_memcache$/d
/^__kvm_nvhe_pkvm_vcpu_init_ptrauth$/d
/^__kvm_nvhe_psci_cpu_suspend$/d
/^__kvm_nvhe_rb_cpu_teardown$/d
/^__kvm_nvhe_stage2_make_pte$/d
/^__kvm_nvhe_trace_host_hcall$/d
/^__kvm_nvhe_unpin_host_vcpu$/d
/^__kvm_read_guest_page$/d
/^__list_add_rcu$/d
/^__lookup_extent_node_ret$/d
/^__lookup_extent_tree$/d
/^__lookup_nat_cache$/d
/^__map_memblock$/d
/^__mark_reg32_known$/d
/^__mark_reg_known$/d
/^__mark_reg_unknown$/d
/^__max_io_len$/d
/^__may_extent_tree$/d
/^__mdb_entry_to_br_ip$/d
/^__mincore_unmapped_range$/d
/^__napi_build_skb$/d
/^__neigh_lookup$/d
/^__netdev_adjacent_dev_unlink_neighbour$/d
/^__netdev_update_lower_level$/d
/^__netdev_update_upper_level$/d
/^__netdev_walk_all_lower_dev$/d
/^__netdev_walk_all_upper_dev$/d
/^__netif_receive_skb$/d
/^__netlink_sendskb$/d
/^__netlink_seq_next$/d
/^__nexthop_replace_notify$/d
/^__nvme_find_path$/d
/^__packet_set_status$/d
/^__page_cache_release$/d
/^__pci_setup_bridge$/d
/^__perf_event_read_size$/d
/^__perf_pmu_install_event$/d
/^__pmem_clear_poison$/d
/^__preempt_count_sub$/d
/^__ptr_ring_consume$/d
/^__ptr_ring_produce$/d
/^__ptrace_may_access$/d
/^__put_system$/d
/^__refill_stock$/d
/^__reg_combine_64_into_32$/d
/^__reg_combine_min_max$/d
/^__register_event$/d
/^__register_prot_hook$/d
/^__relocate_discard_cmd$/d
/^__reset_control_put_internal$/d
/^__rmqueue_pcplist$/d
/^__rt6_find_exception_rcu$/d
/^__rtc_read_time$/d
/^__sb_end_write$/d
/^__sdhci_adma_write_desc$/d
/^__seccomp_filter_release$/d
/^__set_task_blocked$/d
/^__set_test_and_inuse$/d
/^__sha1_ce_transform$/d
/^__sigqueue_alloc$/d
/^__skb_fill_page_desc$/d
/^__skb_queue_purge$/d
/^__skb_tunnel_rx$/d
/^__slab_alloc$/d
/^__slab_err$/d
/^__slab_free$/d
/^__snd_device_free$/d
/^__sock_hash_lookup_elem$/d
/^__sock_set_mark$/d
/^__tcf_bind_filter$/d
/^__tcf_block_find$/d
/^__tcf_generic_walker$/d
/^__tegra_bpmp_channel_write$/d
/^__timerfd_remove_cancel$/d
/^__trace_early_add_event_dirs$/d
/^__tty_perform_flush$/d
/^__tun_build_skb$/d
/^__u32_destroy_key$/d
/^__ublk_abort_rq$/d
/^__udp_manip_pkt$/d
/^__ufshcd_wb_toggle$/d
/^__unmap_stage2_range$/d
/^__update_reg32_bounds$/d
/^__update_reg_bounds$/d
/^__usb_unanchor_urb$/d
/^__uvc_ctrl_get$/d
/^__uvc_find_control$/d
/^__vb2_buf_dmabuf_put$/d
/^__vb2_cleanup_fileio$/d
/^__vb2_plane_dmabuf_put$/d
/^__vgic_its_check_cache$/d
/^__vsock_find_bound_socket$/d
/^__wacom_notify_battery$/d
/^__wait_for_common$/d
/^__wbt_done$/d
/^__xdp_do_redirect_xsk$/d
/^__xfrm_dst_hash$/d
/^__xfrm_policy_link$/d
/^__xfrm_policy_unlink$/d
/^__xfrm_src_hash$/d
/^__xlate_proc_name$/d
/^__xp_dma_unmap$/d
/^_binder_node_lock$/d
/^_compare_exact$/d
/^_detach_genpd$/d
/^_devm_regulator_get_enable$/d
/^_enable_swap_info$/d
/^_find_opp_table_unlocked$/d
/^_fsg_common_free_buffers$/d
/^_fsg_common_remove_luns$/d
/^_put_clks$/d
/^_raw_spin_rq_lock_irqsave$/d
/^_regulator_call_set_voltage_sel$/d
/^_regulator_get_error_flags$/d
/^_regulator_set_voltage_time$/d
/^_set_opp_bw$/d
/^_set_opp_level$/d
/^account_start_copy$/d
/^acct_arg_size$/d
/^adapter_delete_queue$/d
/^add_early_randomness$/d
/^add_generic_implicit_fb$/d
/^add_master_key_user$/d
/^add_mm_rss_vec$/d
/^add_rq_bw$/d
/^add_running_bw$/d
/^add_single_ctl_with_resume$/d
/^add_subprog$/d
/^add_taint_module$/d
/^add_to_list$/d
/^addrconf_add_dev$/d
/^addrconf_dad_kick$/d
/^addrconf_dad_run$/d
/^addrconf_dad_start$/d
/^addrconf_link_ready$/d
/^addrconf_mod_dad_work$/d
/^addrconf_mod_rs_timer$/d
/^addrconf_prefix_route$/d
/^addrconf_sysctl_unregister$/d
/^addrlbl_ifindex_exists$/d
/^adjust_dev_dax_range$/d
/^adjust_unusable_cap_perc$/d
/^aio_free_ring$/d
/^aio_nr_sub$/d
/^aio_prep_rw$/d
/^all_freqs$/d
/^alloc_area$/d
/^alloc_covered_add$/d
/^alloc_file$/d
/^alloc_image_page$/d
/^alloc_io_context$/d
/^alloc_pending_exception$/d
/^alloc_perf_context$/d
/^alloc_rtree_node$/d
/^alloc_task_dma_buf_info$/d
/^alloc_trace_uprobe$/d
/^allocate_cgrp_cset_links$/d
/^allow_has$/d
/^append_md_to_backing_file$/d
/^append_zeros$/d
/^apply_wqattrs_cleanup$/d
/^arm64_show_signal\.rs$/d
/^arm_kprobe$/d
/^arm_v7s_install_table$/d
/^arp_accept$/d
/^arp_devaddr_compare$/d
/^arp_req_set_proxy$/d
/^assign_work$/d
/^asym_fits_cpu$/d
/^atkbd_attr_set_helper$/d
/^atkbd_set_extra$/d
/^atkbd_set_repeat_rate$/d
/^atkbd_set_scroll$/d
/^atkbd_set_set$/d
/^atkbd_set_softraw$/d
/^atkbd_set_softrepeat$/d
/^attach_entity_load_avg$/d
/^attach_mnt$/d
/^audio_format_alloc_init$/d
/^audioformat_free$/d
/^audit_compare_gid$/d
/^audit_compare_uid$/d
/^audit_do_config_change$/d
/^audit_filter_syscall$/d
/^audit_filter_uring$/d
/^audit_get_sk$/d
/^audit_init_watch$/d
/^audit_log_common_recv_msg$/d
/^audit_log_feature_change$/d
/^audit_remove_watch$/d
/^auditd_pid_vnr$/d
/^autoconfig_read_divisor_id$/d
/^avc_alloc_node$/d
/^avc_lookup$/d
/^avc_node_replace$/d
/^avc_xperms_populate$/d
/^backing_inode_security$/d
/^bbr_check_probe_rtt_done$/d
/^bbr_check_time_to_probe_bw$/d
/^bbr_handle_inflight_too_high$/d
/^bbr_inflight$/d
/^bbr_init_pacing_rate_from_rtt$/d
/^bfq_asymmetric_scenario$/d
/^bfq_bfqq_end_wr$/d
/^bfq_bfqq_name$/d
/^bfq_exit_icq_bfqq$/d
/^bfq_idle_extract$/d
/^bfq_may_be_close_cooperator$/d
/^bfq_reset_rate_computation$/d
/^bfq_serv_to_charge$/d
/^bfq_setup_merge$/d
/^bfq_updated_next_req$/d
/^binder_dec_node$/d
/^binder_delete_free_buffer$/d
/^binder_get_node$/d
/^binder_get_node_refs_for_txn$/d
/^binder_inc_node_nilocked$/d
/^binder_insert_free_buffer$/d
/^binder_lru_freelist_add$/d
/^binder_proc_transaction$/d
/^binder_transaction_priority$/d
/^binder_txns_pending_ilocked$/d
/^binder_update_ref_for_handle$/d
/^bio_alloc_cache_prune$/d
/^bio_crypt_ctx_pool$/d
/^bio_next_folio$/d
/^bitmap_copy$/d
/^blk_crypto_find_and_grab_keyslot$/d
/^blk_mq_flush_tag_batch$/d
/^blk_mq_hw_queue_need_run$/d
/^blk_mq_map_bio_put$/d
/^blk_mq_request_issue_directly$/d
/^blk_mq_update_tag_set_shared$/d
/^blk_rq_map_bio_alloc$/d
/^blkdev_dio_unaligned$/d
/^blkdev_put_whole$/d
/^bpf_core_calc_enumval_relo$/d
/^bpf_core_calc_type_relo$/d
/^bpf_ctx_finish$/d
/^bpf_dispatcher_find_prog$/d
/^bpf_get_skb_set_tunnel_proto$/d
/^bpf_iter_udp_realloc_batch$/d
/^bpf_iter_unix_realloc_batch$/d
/^bpf_link_dealloc$/d
/^bpf_map_is_rdonly$/d
/^bpf_mkobj_ops$/d
/^bpf_mprog_pos_after$/d
/^bpf_prog_check_recur$/d
/^bpf_skb_change_protocol$/d
/^bpf_skb_net_hdr_push$/d
/^bpf_struct_ops_map_put_progs$/d
/^bpf_test_init$/d
/^bpf_test_timer_enter$/d
/^bpf_test_timer_leave$/d
/^bpf_tramp_image_put$/d
/^bpf_uprobe_unregister$/d
/^br_fdb_find$/d
/^br_ip4_multicast_add_group$/d
/^br_ip4_multicast_leave_group$/d
/^br_ip4_multicast_mark_router$/d
/^br_ip6_multicast_add_group$/d
/^br_ip6_multicast_leave_group$/d
/^br_ip6_multicast_mark_router$/d
/^br_mdb_ip4_get$/d
/^br_mdb_ip6_get$/d
/^br_multicast_eht_allow$/d
/^br_multicast_eht_block$/d
/^br_multicast_err_count$/d
/^br_multicast_find_port$/d
/^br_multicast_querier_exists$/d
/^br_multicast_router_expired$/d
/^br_multicast_star_g_host_state$/d
/^br_multicast_update_querier$/d
/^br_multicast_update_query_timer$/d
/^br_set_gso_limits$/d
/^break_lease$/d
/^brelse$/d
/^bstats_update$/d
/^bt_subprog_exit$/d
/^bt_tags_for_each$/d
/^btf__resolve_size$/d
/^btf_field_type_name$/d
/^btf_get_module_btf$/d
/^btf_parse_str_sec$/d
/^btf_struct_metas_free$/d
/^btf_type_name$/d
/^btf_type_needs_resolve$/d
/^build_insn$/d
/^build_plt$/d
/^bus_find_device_by_name$/d
/^cache_get$/d
/^cache_mark$/d
/^cache_types$/d
/^calc_index$/d
/^calc_l12_pwron$/d
/^call_fib_entry_notifiers$/d
/^call_ip6mr_mfc_entry_notifiers$/d
/^call_ip6mr_vif_entry_notifiers$/d
/^call_netdevice_notifiers_mtu$/d
/^call_netdevice_register_net_notifiers$/d
/^can_map_frag$/d
/^can_migrate_task$/d
/^can_stop_idle_tick$/d
/^can_vma_merge_before$/d
/^canon_copy_from_read_buf$/d
/^cec_data_completed$/d
/^cec_feature_abort_reason$/d
/^cec_pin_high$/d
/^cec_pin_low$/d
/^cec_pin_read$/d
/^cec_pin_to_idle$/d
/^cgroup_is_valid_domain$/d
/^cgroup_put$/d
/^cgroup_rm_cftypes_locked$/d
/^cgroup_v1v2_get_from_file$/d
/^cgwb_kill$/d
/^change_pageblock_range$/d
/^charge_memcg$/d
/^check_abnormal_return$/d
/^check_brk_limits$/d
/^check_buffer_access$/d
/^check_canary$/d
/^check_cand_cache$/d
/^check_conflicting_open$/d
/^check_ids$/d
/^check_input_term$/d
/^check_insane_mems_config$/d
/^check_kfunc_call$/d
/^check_loop$/d
/^check_max_stack_depth_subprog$/d
/^check_new_pages$/d
/^check_packet_access$/d
/^check_pointer$/d
/^check_reference_leak$/d
/^check_reset_of_active_ep$/d
/^check_scalar_ids$/d
/^check_valid_map$/d
/^checkintf$/d
/^class_decode$/d
/^cleaned$/d
/^cleanup_entry$/d
/^cleanup_prefix_route$/d
/^clear_hub_feature$/d
/^clear_page_private_all$/d
/^clear_page_private_atomic$/d
/^clear_tracing_err_log$/d
/^clear_user_highpage$/d
/^clear_young_dirty_ptes$/d
/^client_drop_item$/d
/^clk_core_get_scaled_duty_cycle$/d
/^clk_core_has_parent$/d
/^clk_core_hold_state$/d
/^clk_core_init_rate_req$/d
/^clk_core_is_prepared$/d
/^clk_core_link_consumer$/d
/^clk_core_lookup$/d
/^clk_core_prepare_lock$/d
/^clk_core_reparent_orphans$/d
/^clk_core_unprepare_lock$/d
/^clk_fd_get_div$/d
/^clk_prepare_enable$/d
/^clk_reparent$/d
/^clockevents_config$/d
/^clockevents_program_min_delta$/d
/^cls_bpf_free_parms$/d
/^cn_vprintf$/d
/^coalesce_put_bool$/d
/^collect_langs$/d
/^collect_mm_slot$/d
/^commit_echoes$/d
/^compact_lock_irqsave$/d
/^compat_fetch_robust_entry$/d
/^compat_get_user_reg$/d
/^compat_standard_call$/d
/^complete_signal$/d
/^complete_walk$/d
/^compute_effective_cpumask$/d
/^compute_tt_budget$/d
/^configfs_detach_group$/d
/^configfs_put$/d
/^configfs_remove_dir$/d
/^configfs_remove_dirent$/d
/^connector_bad_edid$/d
/^console_is_registered$/d
/^consume_target_dsq$/d
/^consume_ux_dsq$/d
/^context_write$/d
/^contpte_convert$/d
/^copy_from_bpfptr_offset$/d
/^copy_from_page$/d
/^copy_from_read_buf$/d
/^copy_from_user_policy$/d
/^copy_kprobe$/d
/^copy_reference_state$/d
/^copy_sec_ctx$/d
/^copy_to_bpfptr_offset$/d
/^copy_user_offload$/d
/^copyout$/d
/^count_configs$/d
/^cpu_overutilized$/d
/^cpufreq_exit_governor$/d
/^cpufreq_parse_policy$/d
/^cpufreq_policy_put_kobj$/d
/^cpufreq_verify_current_freq$/d
/^cpuhp_kick_ap$/d
/^cpuidle_remove_state_sysfs$/d
/^cpumask_distribute_next$/d
/^cpuset_attach_nodemask_to\.0$/d
/^crc32_validate$/d
/^create_boost_sysfs_file$/d
/^create_filter_start$/d
/^crtc_or_fake_commit$/d
/^crypto_ahash_op$/d
/^crypto_larval_wait$/d
/^crypto_remove_instance$/d
/^css_get$/d
/^css_tryget$/d
/^csum_and_memcpy$/d
/^ctnetlink_change_mark$/d
/^ctnetlink_change_protoinfo$/d
/^ctnetlink_dump_acct$/d
/^ctnetlink_dump_ct_seq_adj$/d
/^ctnetlink_dump_mark$/d
/^ctnetlink_dump_master$/d
/^ctnetlink_dump_protoinfo$/d
/^ctnetlink_dump_timeout$/d
/^ctnetlink_dump_tuples$/d
/^ctnetlink_exp_fill_info$/d
/^ctnetlink_parse_help$/d
/^ctx_groups_sched_in$/d
/^current_sit_addr$/d
/^d_delete_notify$/d
/^damon_sysfs_kdamond_running$/d
/^damon_sysfs_kdamonds_rm_dirs$/d
/^damon_sysfs_targets_rm_dirs$/d
/^dapm_connect_mux$/d
/^dapm_free_path$/d
/^dapm_widget_invalidate_input_paths$/d
/^dapm_widget_invalidate_output_paths$/d
/^days_since_leapyear$/d
/^days_since_year$/d
/^dec_count$/d
/^dec_slabs_node$/d
/^del_page_from_free_list$/d
/^del_usage_links$/d
/^delete_node$/d
/^delete_partition$/d
/^delete_tempaddrs$/d
/^deliver_ptype_list_skb$/d
/^dell_dock_mixer_init$/d
/^dentry_unlink_inode$/d
/^dequeue_rt_stack$/d
/^dequeue_top_rt_rq$/d
/^descriptor_loc$/d
/^destroy_async_on_interface$/d
/^destroy_device_list$/d
/^destroy_obj_hashfn$/d
/^destroy_percpu_info$/d
/^destroy_sched_domain$/d
/^destroy_swap_extents$/d
/^detach_entity_load_avg$/d
/^detach_if_pending$/d
/^detach_task$/d
/^dev_get_hwtstamp_phylib$/d
/^dev_index_reserve$/d
/^dev_map_enqueue_clone$/d
/^dev_put$/d
/^dev_validate_header$/d
/^dev_xdp_install$/d
/^device_init_wakeup$/d
/^device_link_init_status$/d
/^device_links_flush_sync_list$/d
/^device_remove$/d
/^devlink_trap_group_unregister$/d
/^devlink_trap_stats_read$/d
/^devlink_trap_unregister$/d
/^devres_log$/d
/^dfll_request_rate$/d
/^dfll_set_default_params$/d
/^die_kernel_fault$/d
/^dio_zero_block$/d
/^dispatch_job$/d
/^dm_exception_table_exit$/d
/^dm_exception_table_init$/d
/^dm_exception_table_unlock$/d
/^dm_io_dec_pending$/d
/^dm_lookup_exception$/d
/^dm_requeue_original_request$/d
/^dm_stat_round$/d
/^dm_zone_unlock$/d
/^dma_buf_poll_add_cb$/d
/^dma_chan_put$/d
/^dma_device_release$/d
/^dma_map_single_attrs$/d
/^dma_set_mask_and_coherent$/d
/^do_add_mount$/d
/^do_dentry_open$/d
/^do_one_tree$/d
/^do_page_mkwrite$/d
/^do_set_master$/d
/^do_write_page$/d
/^dont_mount$/d
/^dpm_propagate_wakeup_to_parent$/d
/^dpm_run_callback$/d
/^dpm_show_time$/d
/^dquot_free_block$/d
/^drain_pages$/d
/^drm_edid_override_get$/d
/^drm_gem_object_handle_get$/d
/^drm_mode_create_colorspace_property$/d
/^drm_mode_parse_cmdline_int$/d
/^drm_new_set_master$/d
/^drm_set_master$/d
/^drm_syncobj_array_free$/d
/^drm_syncobj_assign_null_handle$/d
/^drm_syncobj_fence_get$/d
/^drm_syncobj_put$/d
/^dsq_id_to_internal$/d
/^dst_cache_per_cpu_get$/d
/^dualsense_init_output_report$/d
/^dualsense_schedule_work$/d
/^dualsense_send_output_report$/d
/^dualsense_set_lightbar$/d
/^dualshock4_schedule_work$/d
/^dualshock4_set_default_lightbar_colors$/d
/^dump_buff_as_hex$/d
/^dump_counters$/d
/^dump_ct_seq_adj$/d
/^dump_interrupted$/d
/^duplicate_memory_bitmap$/d
/^dwc3_clk_disable$/d
/^dwc3_clk_enable$/d
/^dwc3_core_init_for_resume$/d
/^dwc3_ep0_delegate_req$/d
/^dwc3_ep0_prepare_one_trb$/d
/^dwc3_ep0_reset_state$/d
/^dwc3_free_event_buffers$/d
/^dwc3_gadget_calc_ram_depth$/d
/^dwc3_phy_exit$/d
/^dwc3_phy_power_off$/d
/^dwc3_prepare_last_sg$/d
/^dwc3_prepare_trbs_sg$/d
/^dwc3_qcom_interconnect_exit$/d
/^dwc3_qcom_vbus_override_enable$/d
/^dx_insert_block$/d
/^dx_node_limit$/d
/^dx_root_limit$/d
/^dyn_event_add$/d
/^dynptr_get_type$/d
/^dynptr_id$/d
/^dynptr_ref_obj_id$/d
/^dynptr_type_str$/d
/^echo_char$/d
/^echo_erase_tab$/d
/^edid_hfeeodb_block_count$/d
/^efi_mem_reserve_iomem$/d
/^ehci_clear_tt_buffer$/d
/^ehci_enable_event$/d
/^ehci_port_power$/d
/^ehci_urb_done$/d
/^enable_best_rng$/d
/^enable_periodic$/d
/^enqueue_top_rt_rq$/d
/^env_stack_push$/d
/^env_type_is_resolve_sink$/d
/^ep_item_poll$/d
/^ep_set_busy_poll_napi_id$/d
/^ep_unregister_pollwait$/d
/^error_tg_ok$/d
/^errpos$/d
/^erspan_build_header$/d
/^erspan_build_header_v2$/d
/^es_do_reclaim_extents$/d
/^esp_output_fill_trailer$/d
/^established_get_next$/d
/^eth_start$/d
/^ethnl_bitmap32_clear$/d
/^ethnl_udp_table_reply_size$/d
/^ethtool_copy_validate_indir$/d
/^ethtool_get_feature_mask$/d
/^ethtool_phy_tunable_valid$/d
/^ethtool_rxnfc_copy_struct$/d
/^ethtool_set_value$/d
/^ethtool_tunable_valid$/d
/^ethtool_vzalloc_stats_array$/d
/^event_delays_ns$/d
/^event_sched_in$/d
/^exclusive_event_destroy$/d
/^exclusive_event_installable$/d
/^exfat_extract_uni_name$/d
/^exfat_make_attr$/d
/^ext4_begin_ordered_truncate$/d
/^ext4_block_truncate_page$/d
/^ext4_clear_request_list$/d
/^ext4_dx_csum$/d
/^ext4_ext_get_access$/d
/^ext4_ext_zeroout$/d
/^ext4_extent_block_csum_set$/d
/^ext4_fc_add_tlv$/d
/^ext4_find_entry$/d
/^ext4_flex_groups_free$/d
/^ext4_generic_write_checks$/d
/^ext4_group_desc_free$/d
/^ext4_has_group_desc_csum$/d
/^ext4_inc_count$/d
/^ext4_init_journal_params$/d
/^ext4_issue_discard$/d
/^ext4_journal_abort_handle$/d
/^ext4_journal_ensure_credits$/d
/^ext4_lock_group$/d
/^ext4_mb_mark_pa_deleted$/d
/^ext4_mb_pa_free$/d
/^ext4_mb_pa_put_free$/d
/^ext4_mb_unload_buddy$/d
/^ext4_num_base_meta_clusters$/d
/^ext4_percpu_param_destroy$/d
/^ext4_rereserve_cluster$/d
/^ext4_should_dioread_nolock$/d
/^ext4_split_convert_extents$/d
/^ext4_truncate_folio$/d
/^ext4_update_dir_count$/d
/^ext4_update_dx_flag$/d
/^ext4_update_final_de$/d
/^ext4_update_i_disksize$/d
/^ext4_update_inode_fsync_trans$/d
/^ext4_update_inode_size$/d
/^ext4_xattr_block_cache_insert$/d
/^ext4_xattr_block_csum_set$/d
/^ext4_xattr_inode_free_quota$/d
/^ext4_xattr_value_same$/d
/^ext4_zeroout_es$/d
/^f2fs_buffered_write_iter$/d
/^f2fs_checkpoint_chksum$/d
/^f2fs_crc32$/d
/^f2fs_data_blkaddr$/d
/^f2fs_gc_pinned_control$/d
/^f2fs_grab_cache_page$/d
/^f2fs_i_blocks_write$/d
/^f2fs_inode_chksum$/d
/^f2fs_io_schedule_timeout$/d
/^f2fs_meta_inode_gc_required$/d
/^f2fs_put_rpages$/d
/^f2fs_set_compressed_page$/d
/^f2fs_should_use_dio$/d
/^f2fs_truncate_meta_inode_pages$/d
/^failed_creating$/d
/^fat_calc_dir_size$/d
/^fat_make_attrs$/d
/^fat_trim_clusters$/d
/^fault_info$/d
/^fault_signal_pending$/d
/^fdb_del_hw_addr$/d
/^fdb_to_nud$/d
/^fdb_vid_parse$/d
/^fdt_blocks_misordered_$/d
/^fdt_splice_$/d
/^fetch_robust_entry$/d
/^ffs_do_descs$/d
/^ffs_epfiles_destroy$/d
/^ffs_sb_create_file$/d
/^fib6_check_nh_list$/d
/^fib6_dump_end$/d
/^fib6_info_nh_dev$/d
/^fib_disable_ip$/d
/^fib_info_hashfn$/d
/^fib_notify_alias_delete$/d
/^fib_result_assign$/d
/^fib_rule_put$/d
/^file_map_prot_check$/d
/^filemap_fdatawait$/d
/^filemap_unaccount_folio$/d
/^fill_contig_page_info$/d
/^fill_route_from_fnhe$/d
/^fill_temp$/d
/^finalize_log$/d
/^find_file_var$/d
/^find_first_overlapping_range$/d
/^find_format_by_pix$/d
/^find_get_entry$/d
/^find_master_key_user$/d
/^find_next_mappable_frag$/d
/^find_or_evict$/d
/^find_pmd_or_thp_or_none$/d
/^find_ppage$/d
/^find_prev_entry$/d
/^find_probe_event$/d
/^find_sec$/d
/^find_set_and_id$/d
/^find_subprog$/d
/^find_trace_kprobe$/d
/^find_unlink_vmap_area$/d
/^find_uprobe$/d
/^find_var$/d
/^findintfep$/d
/^fl_free$/d
/^fl_link$/d
/^fl_lookup$/d
/^fmt_reg_mask$/d
/^fmt_stack_mask$/d
/^fold_diff$/d
/^folio_alloc$/d
/^folio_fast_pin_allowed$/d
/^folio_needs_release$/d
/^folio_not_mapped$/d
/^folio_prealloc$/d
/^folio_pte_batch$/d
/^folio_zero_segment$/d
/^fprop_reflect_period_percpu$/d
/^fpsimd_bind_task_to_cpu$/d
/^fq_dequeue_skb$/d
/^fq_flow_unset_throttled$/d
/^free_aggregate_device$/d
/^free_all$/d
/^free_area$/d
/^free_ei$/d
/^free_ep_req$/d
/^free_event$/d
/^free_exit_list$/d
/^free_ext_block$/d
/^free_flex_gd$/d
/^free_func_state$/d
/^free_image_page$/d
/^free_notes_attrs$/d
/^free_params$/d
/^free_pending_exception$/d
/^free_pg_vec$/d
/^free_poll_entry$/d
/^free_predicate$/d
/^free_sect_attrs$/d
/^free_substream$/d
/^free_thread_stack$/d
/^free_trace_uprobe$/d
/^free_unmap_vmap_area$/d
/^free_unref_page_commit$/d
/^free_var_defs$/d
/^free_verifier_state$/d
/^fs_dtype_by_ftype$/d
/^fscontext_create_fd$/d
/^fscrypt_get_policy$/d
/^fscrypt_initiate_key_removal$/d
/^fsleep$/d
/^fsnotify_create$/d
/^fsnotify_delete$/d
/^fsnotify_detach_connector_from_object$/d
/^fsnotify_inode$/d
/^fsnotify_perm$/d
/^fsnotify_xattr$/d
/^fsverity_read_buffer$/d
/^function_descriptors$/d
/^fuse_invalidate_entry$/d
/^fuse_readlink_page$/d
/^fuse_release_user_pages$/d
/^fuse_writepage_finish$/d
/^futex_cleanup$/d
/^fwnode_devcon_matches$/d
/^fwnode_links_purge_consumers$/d
/^fwnode_links_purge_suppliers$/d
/^gen_new_kid$/d
/^generic_ci_d_compare$/d
/^generic_ci_d_hash$/d
/^generic_ci_dentry_ops$/d
/^generic_encrypted_ci_dentry_ops$/d
/^generic_encrypted_dentry_ops$/d
/^generic_exec_single$/d
/^geni_se_clks_off$/d
/^genpd_update_accounting$/d
/^get_available_block_count$/d
/^get_bitmap$/d
/^get_bits$/d
/^get_ccsidr$/d
/^get_cluster_channels_v3$/d
/^get_ctl_id_hash$/d
/^get_data_file_block$/d
/^get_dnode_addr$/d
/^get_dynptr_arg_reg$/d
/^get_ei$/d
/^get_ext_path$/d
/^get_file_raw_ptr$/d
/^get_governor$/d
/^get_incfs_data_file$/d
/^get_mtime$/d
/^get_node_path$/d
/^get_params$/d
/^get_pid$/d
/^get_pmu_ctx$/d
/^get_pte_pfn$/d
/^get_random_u32_inclusive$/d
/^get_slot_next$/d
/^get_swappiness$/d
/^get_uid$/d
/^get_utask$/d
/^ghash_do_update$/d
/^gic_dist_wait_for_rwp$/d
/^gic_peek_irq$/d
/^gic_teardown$/d
/^gpiochip_allocate_mask$/d
/^gpiochip_free_hogs$/d
/^gpiochip_irqchip_add_allocated_domain$/d
/^gpiochip_setup_dev$/d
/^grow_tree_refs$/d
/^gs_free_requests$/d
/^guid_equal$/d
/^gunyah_error_remap$/d
/^gunyah_vcpu_check_system$/d
/^handle_exit_race$/d
/^handshake$/d
/^handshake_init$/d
/^hardware_disable_all$/d
/^hardware_disable_all_nolock$/d
/^hash_ip4_ahash_destroy$/d
/^hash_ip6_ahash_destroy$/d
/^hash_ipmac4_ahash_destroy$/d
/^hash_ipmac6_ahash_destroy$/d
/^hash_ipmark4_ahash_destroy$/d
/^hash_ipmark6_ahash_destroy$/d
/^hash_ipport4_ahash_destroy$/d
/^hash_ipport6_ahash_destroy$/d
/^hash_ipportip4_ahash_destroy$/d
/^hash_ipportip6_ahash_destroy$/d
/^hash_ipportnet4_ahash_destroy$/d
/^hash_ipportnet4_del_cidr$/d
/^hash_ipportnet6_ahash_destroy$/d
/^hash_mac4_ahash_destroy$/d
/^hash_net4_ahash_destroy$/d
/^hash_net4_del_cidr$/d
/^hash_net6_ahash_destroy$/d
/^hash_netiface4_ahash_destroy$/d
/^hash_netiface4_del_cidr$/d
/^hash_netiface6_ahash_destroy$/d
/^hash_netnet4_ahash_destroy$/d
/^hash_netnet4_del_cidr$/d
/^hash_netnet6_ahash_destroy$/d
/^hash_netport4_ahash_destroy$/d
/^hash_netport4_del_cidr$/d
/^hash_netport6_ahash_destroy$/d
/^hash_netportnet4_ahash_destroy$/d
/^hash_netportnet4_del_cidr$/d
/^hash_netportnet6_ahash_destroy$/d
/^hash_one_block$/d
/^hashlimit_pernet$/d
/^hashtab_insert$/d
/^have_full_constraints$/d
/^hctr2_finish$/d
/^hctr2_hash_tweaklen$/d
/^hi_lo_writeq$/d
/^hib_init_batch$/d
/^hibernation_test$/d
/^hid_get_class_descriptor$/d
/^hid_map_usage$/d
/^hid_map_usage_clear$/d
/^hid_report_release_tool$/d
/^hid_report_set_tool$/d
/^hiddev_lookup_report$/d
/^hidpp10_query_battery_mileage$/d
/^hidpp10_set_register$/d
/^hidpp_prefix_name$/d
/^hidpp_root_get_feature$/d
/^hidpp_scroll_counter_handle_scroll$/d
/^hidpp_send_fap_command_sync$/d
/^hlist_bl_unlock$/d
/^housekeeping$/d
/^ht_check_msi_mapping$/d
/^htab_free_elems$/d
/^htb_add_to_wait_tree$/d
/^htb_find$/d
/^htb_graft_helper$/d
/^htb_parent_to_leaf_offload$/d
/^hub_power_on$/d
/^hugepage_vma_revalidate$/d
/^hung_up_tty_compat_ioctl$/d
/^hung_up_tty_fasync$/d
/^hung_up_tty_fops$/d
/^hung_up_tty_ioctl$/d
/^hung_up_tty_poll$/d
/^hung_up_tty_read$/d
/^hung_up_tty_write$/d
/^hw_support_mmap$/d
/^hyp_s1_pgtable_pages$/d
/^hyp_trace_teardown_pages$/d
/^i2c_do_del_adapter$/d
/^i2c_smbus_try_get_dmabuf$/d
/^i3c_master_alloc_i3c_dev$/d
/^i3c_master_attach_i2c_dev$/d
/^i3c_master_detach_i2c_dev$/d
/^i3c_master_detach_i3c_dev$/d
/^i3c_master_enec_disec_locked$/d
/^i3c_master_rstdaa_locked$/d
/^i3c_master_send_ccc_cmd_locked$/d
/^i3c_master_setda_locked$/d
/^icmp_socket_deliver$/d
/^icmp_xmit_lock$/d
/^icmpv4_global_allow$/d
/^icmpv6_global_allow$/d
/^icmpv6_xmit_lock$/d
/^id_to_memslot$/d
/^id_to_sys_reg_desc$/d
/^idling_needed_for_service_guarantees$/d
/^igmp_ifc_event$/d
/^igmp_stop_timer$/d
/^igmpv3_sendpack$/d
/^iio_buffer_add_demux$/d
/^iio_buffer_deactivate$/d
/^iio_compute_scan_bytes$/d
/^iio_scan_mask_match$/d
/^iio_storage_bytes_for_timestamp$/d
/^in6_dev_get$/d
/^in6_dev_put$/d
/^in6_ifa_put$/d
/^in_rbtree_lock_required_cb$/d
/^incfs_set_verity_digest$/d
/^index_update$/d
/^inet_abc_len$/d
/^info_bdq_free$/d
/^info_idq_free$/d
/^init_cgroup_housekeeping$/d
/^init_cur_mix_raw$/d
/^init_trace_flags_index$/d
/^initcall_debug_report$/d
/^initcall_debug_start$/d
/^inode_free_by_rcu$/d
/^inode_needs_update_time$/d
/^input_add_uevent_bm_var$/d
/^input_dev_release_keys$/d
/^input_print_modalias$/d
/^insert_revoke_hash$/d
/^insert_to_prio_queue$/d
/^insert_work$/d
/^insn_def_regno$/d
/^install_unbound_pwq$/d
/^interpret_urb_result$/d
/^invalidate_snapshot$/d
/^io_alloc_hash_table$/d
/^io_assign_file$/d
/^io_buffer_add_list$/d
/^io_eventfd_signal$/d
/^io_fill_cqe_aux$/d
/^io_msg_exec_remote$/d
/^io_poll_get_ownership$/d
/^io_poll_remove_entries$/d
/^io_prep_async_link$/d
/^io_rw_should_reissue$/d
/^io_setup_async_addr$/d
/^io_unregister_personality$/d
/^io_wq_activate_free_worker$/d
/^io_wq_cancel_tw_create$/d
/^io_wq_for_each_worker$/d
/^io_wq_worker_affinity$/d
/^io_wq_worker_cancel$/d
/^io_wq_worker_wake$/d
/^ioc_start_period$/d
/^iocb_destroy$/d
/^iocg_commit_bio$/d
/^iopte_deref$/d
/^ip4_dst_hoplimit$/d
/^ip6_dst_store$/d
/^ip6_nh_lookup_table$/d
/^ip6_rcv_finish_core$/d
/^ip6_tnl_update$/d
/^ip6gre_tnl_parm_to_user$/d
/^ip6gre_tunnel_find$/d
/^ip6gre_tunnel_link$/d
/^ip6gre_tunnel_unlink$/d
/^ip6mr_new_table$/d
/^ip6mr_rules_exit$/d
/^ip6mr_update_thresholds$/d
/^ip_ma_put$/d
/^ip_mc_may_pull$/d
/^ip_neigh_gw4$/d
/^ip_neigh_gw6$/d
/^ip_route_input_rcu$/d
/^ip_route_output_ports$/d
/^ip_tunnel_add$/d
/^ipip6_tunnel_locate$/d
/^ipv4_portaddr_hash$/d
/^ipv6_addr_cmp$/d
/^ipv6_addr_prefix$/d
/^ipv6_mc_config$/d
/^ipv6_mc_may_pull$/d
/^ipv6_rcv_saddr_equal$/d
/^ipv6_route_seq_setup_walk$/d
/^ir_free_table$/d
/^irq_domain_fix_revmap$/d
/^irqfd_update$/d
/^irqtime_account_process_tick$/d
/^is_acquire_function$/d
/^is_descending$/d
/^is_flex_arr$/d
/^is_kfunc_arg_const_mem_size$/d
/^is_ptr_cast_function$/d
/^is_refcount_suitable$/d
/^is_sync_callback_calling_insn$/d
/^is_trusted_reg$/d
/^iso_sched_free$/d
/^iter_state_str$/d
/^iter_type_str$/d
/^its_clear_vpend_valid$/d
/^its_free_ite$/d
/^its_send_vmovi$/d
/^journal_shrink_one_cp_list$/d
/^kauditd_rehold_skb$/d
/^kcopyd_put_pages$/d
/^key_get$/d
/^keyctl_change_reqkey_auth$/d
/^kick_hub_wq$/d
/^kill_css$/d
/^kone_check_write$/d
/^kone_get_settings$/d
/^kone_set_settings$/d
/^kone_set_settings_checksum$/d
/^kone_tcu_command$/d
/^ktime_get_coarse$/d
/^kvm_arm_setup_mdcr_el2$/d
/^kvm_get_vcpu$/d
/^kvm_handle_cp_32$/d
/^kvm_io_bus_destroy$/d
/^kvm_pmu_set_pmc_value$/d
/^kvm_timer_compute_delta$/d
/^kvm_timer_vcpu_load_gic$/d
/^kvm_vfio_file_set_kvm$/d
/^kvm_vfio_update_coherency$/d
/^kvmemdup_bpfptr$/d
/^kzalloc_node$/d
/^legitimize_links$/d
/^lg_g15_init_input_dev$/d
/^lg_g15_register_led$/d
/^lg_g15_update_led_brightness$/d
/^lg_g510_update_mkey_led_brightness$/d
/^limit_reserve_root$/d
/^linehandle_free$/d
/^linehandle_validate_flags$/d
/^link_css_set$/d
/^link_obj$/d
/^list_add_rcu$/d
/^list_del_rcu$/d
/^listening_get_first$/d
/^listening_get_next$/d
/^lock_parent$/d
/^locks_init_lock_heads\.__key$/d
/^locks_translate_pid$/d
/^logi_dj_recv_queue_notification$/d
/^logi_dj_recv_queue_unknown_work$/d
/^logi_hidpp_dev_conn_notif_equad$/d
/^lookup_all_xattrs$/d
/^lookup_device_name$/d
/^lookup_fast$/d
/^lookup_interface$/d
/^lookup_nulls_elem_raw$/d
/^lookup_string$/d
/^loop_config_discard$/d
/^loop_flag_is_zero$/d
/^loop_remove$/d
/^loop_reread_partitions$/d
/^loop_set_size$/d
/^loop_validate_file$/d
/^lpi_write_config$/d
/^lrng_set_operational$/d
/^lru_evict$/d
/^lsm_file_cache$/d
/^lsm_inode_cache$/d
/^ma_put$/d
/^mab_calc_split$/d
/^mab_shift_right$/d
/^madvise_update_vma$/d
/^mall_destroy_hw_filter$/d
/^mark_btf_func_reg_size$/d
/^mark_btf_ld_reg$/d
/^mark_ptr_not_null_reg$/d
/^mark_reg_graph_node$/d
/^mark_reg_invalid$/d
/^mark_reg_known_zero$/d
/^mas_find_child$/d
/^mas_find_rev_setup$/d
/^mas_find_setup$/d
/^mas_leaf_set_meta$/d
/^mas_next_setup$/d
/^mas_next_sibling$/d
/^mas_next_slot$/d
/^mas_prev_setup$/d
/^mas_prev_sibling$/d
/^mas_skip_node$/d
/^mas_store_b_node$/d
/^mas_wr_end_piv$/d
/^mas_wr_walk_descend$/d
/^mas_wr_walk_index$/d
/^match_either_id$/d
/^may_change_propagation$/d
/^may_link$/d
/^may_update_sockmap$/d
/^may_use_simd$/d
/^maybe_deliver$/d
/^mb_cache_entry_put$/d
/^mb_clear_bits$/d
/^mb_find_buddy$/d
/^mb_test_and_clear_bits$/d
/^mbox3_setup_48_24_magic$/d
/^media_pipeline_add_pad$/d
/^media_request_clean$/d
/^mem_cgroup_clear_mc$/d
/^memalloc_retry_wait$/d
/^memblock_insert_region$/d
/^memcg_slab_free_hook$/d
/^memcpy_from_msg$/d
/^memdup_sockptr$/d
/^memory_block_memmap_on_memory_pages$/d
/^memsize_get_new_rgn$/d
/^message_ephemeral$/d
/^mext_check_coverage$/d
/^migrate_folio_done$/d
/^mld_clear_delrec$/d
/^mld_ifc_event$/d
/^mld_in_v1_mode$/d
/^mls_read_level$/d
/^mls_write_level$/d
/^mm_alloc_pmd$/d
/^mmc_blk_ioctl_copy_from_user$/d
/^mmc_blk_part_switch$/d
/^mmc_blk_remove_parts$/d
/^mmc_blk_reset$/d
/^mmc_part_add$/d
/^mmc_sdio_switch_hs$/d
/^mmc_spi_err_check$/d
/^mmc_spi_send_cxd$/d
/^mmu_memory_cache_alloc_obj$/d
/^mntput_no_expire$/d
/^moan_device$/d
/^module_unload_free$/d
/^mr_cache_put$/d
/^mrq_debug_close$/d
/^msi_domain_add_simple_msi_descs$/d
/^mt_store_field$/d
/^n_tty_check_unthrottle$/d
/^n_tty_receive_handle_newline$/d
/^n_tty_receive_signal_char$/d
/^napi_frag_unref$/d
/^nbp_update_port_count$/d
/^nd_jump_root$/d
/^nd_label_base$/d
/^nd_label_copy$/d
/^ndisc_alloc_skb$/d
/^ndisc_fill_addr_option$/d
/^neigh_event_send$/d
/^neigh_mark_dead$/d
/^neon_poly1305_blocks$/d
/^netdev_name_node_add$/d
/^netdev_put$/d
/^netdev_reg_state$/d
/^netif_freeze_queues$/d
/^netif_testing_off$/d
/^netif_unfreeze_queues$/d
/^netlink_undo_bind$/d
/^next_entry$/d
/^next_tgid$/d
/^nexthop_alloc$/d
/^nexthop_put$/d
/^nexthops_dump$/d
/^nf_conntrack_double_lock$/d
/^nf_ct_exp_equal$/d
/^nf_hook$/d
/^nf_reject_iphdr_validate$/d
/^nf_reject_verify_csum$/d
/^nfct_help$/d
/^nfct_help_data$/d
/^nfnl_err_reset$/d
/^nfqnl_reinject$/d
/^nh_hthr_group_rebalance$/d
/^nh_notifier_mpath_info_init$/d
/^nh_res_group_rebalance$/d
/^nla_get_msecs$/d
/^nla_get_s64$/d
/^nla_get_u64$/d
/^nla_parse_nested$/d
/^nla_put_ipaddr4$/d
/^nla_put_ipaddr6$/d
/^nlmsg_parse_deprecated_strict$/d
/^node_set_marks$/d
/^notify_xrun$/d
/^ntp_next_leap_sec$/d
/^num_clusters_in_group$/d
/^number_of_same_symbols$/d
/^nvdimm_account_cleared_poison$/d
/^nvme_dbbuf_dma_free$/d
/^nvme_dev_remove_admin$/d
/^nvme_init_queue$/d
/^nvme_ns_open$/d
/^nvme_release_prp_pools$/d
/^nvme_set_host_mem$/d
/^nvme_set_ref_tag$/d
/^nvme_setup_rw$/d
/^nvme_start_keep_alive$/d
/^nvme_submit_cmds$/d
/^nvme_wait_ready$/d
/^nvmem_cell_read_variable_common$/d
/^nvmem_create_cell$/d
/^nvmem_device_remove_all_cells$/d
/^nvmem_reg_read$/d
/^obj_cgroup_charge_pages$/d
/^obj_cgroup_uncharge_pages$/d
/^ocontext_destroy$/d
/^of_count_cache_leaves$/d
/^of_gpio_quirk_polarity$/d
/^of_property_present$/d
/^of_property_read_bool$/d
/^ovl_check_layer$/d
/^ovl_copy_up_data$/d
/^ovl_dir_reset$/d
/^ovl_do_getxattr$/d
/^ovl_do_rename$/d
/^ovl_drop_nlink$/d
/^ovl_prep_cu_creds$/d
/^ovl_reset_lowerdirs$/d
/^ovl_revert_cu_creds$/d
/^ovl_set_opaque_xerr$/d
/^ovl_set_timestamps$/d
/^ovl_setup_trap$/d
/^ovl_verify_fh$/d
/^packet_read_pending$/d
/^packet_sock_flag_set$/d
/^padzero$/d
/^page_array_alloc$/d
/^page_bad_reason$/d
/^page_mapcount$/d
/^page_pool_dma_map$/d
/^partition_is_populated$/d
/^path_overmounted$/d
/^pci_clear_and_set_dword$/d
/^pci_create_resource_files$/d
/^pci_iov_set_numvfs$/d
/^pci_mmap_resource$/d
/^pci_read_bases$/d
/^pci_read_irq$/d
/^pci_rebar_find_pos$/d
/^pci_setup_bridge_mmio$/d
/^pci_setup_msi_context$/d
/^pcie_config_aspm_path$/d
/^pcie_set_clkpm$/d
/^pcp_allowed_order$/d
/^pcpu_next_fit_region$/d
/^pcs_pinconf_clear_bias$/d
/^perf_adjust_freq_unthr_context$/d
/^perf_ctx_disable$/d
/^perf_ctx_enable$/d
/^perf_event__header_size$/d
/^perf_event__id_header_size$/d
/^perf_get_aux_event$/d
/^perf_remove_from_context$/d
/^perf_unpin_context$/d
/^persistent_ram_update$/d
/^pfkey_sadb2xfrm_user_sec_ctx$/d
/^pfkey_sockaddr_extract$/d
/^pfn_valid$/d
/^phy_leds_unregister$/d
/^phy_modes$/d
/^phylink_link_down$/d
/^phylink_mac_initial_config$/d
/^phylink_mac_pcs_get_state$/d
/^pi_state_update_owner$/d
/^pick_file$/d
/^pick_next_pushable_dl_task$/d
/^pinctrl_free_pindescs$/d
/^pinctrl_gpio_direction$/d
/^ping_get_idx$/d
/^pkvm_host_fp_state_order$/d
/^pkvm_unmap_module_sections$/d
/^pl011_disable_interrupts$/d
/^pl011_dmabuf_free$/d
/^pl011_read$/d
/^pl011_tx_char$/d
/^pm_late_early_op$/d
/^pm_noirq_op$/d
/^pm_op$/d
/^pm_sleep_disable_secondary_cpus$/d
/^pmem_clear_bb$/d
/^pointer_string$/d
/^pop_stack$/d
/^pr_cont_work$/d
/^prb_dispatch_next_block$/d
/^prb_open_block$/d
/^prealloc_destroy$/d
/^prealloc_lru_pop$/d
/^preallocate_image_memory$/d
/^prep_new_page$/d
/^prepare_alloc_pages$/d
/^prepare_ip6gre_xmit_ipv4$/d
/^prepare_kill_siginfo$/d
/^prepare_signal$/d
/^print_bad_pte$/d
/^print_fn_trace$/d
/^print_insn_state$/d
/^printk_console_no_auto_verbose$/d
/^prio_offload$/d
/^process_h245_channel$/d
/^propagate_weights$/d
/^pskb_may_pull_reason$/d
/^pskb_pull$/d
/^pskb_trim$/d
/^pte_alloc_one$/d
/^ptep_clear$/d
/^ptep_get_and_clear$/d
/^ptrace_hbp_set_addr$/d
/^ptrace_link$/d
/^ptrace_parent_sid$/d
/^ptrace_setsiginfo$/d
/^ptrace_traceme$/d
/^ptype_get_idx$/d
/^purge_cand_cache$/d
/^push_jmp_history$/d
/^put_aio_ring_file$/d
/^put_dev_sector$/d
/^put_entry$/d
/^put_int$/d
/^put_net$/d
/^put_nsproxy$/d
/^put_rng$/d
/^put_tree_ref$/d
/^put_u64$/d
/^put_uint$/d
/^put_ushort$/d
/^pwm_class_resume_npwm$/d
/^pwq_dec_nr_in_flight$/d
/^qcom_ep_reset_assert$/d
/^qcom_pcie_clear_hpc$/d
/^qdisc_purge_queue$/d
/^qdisc_qstats_cpu_backlog_dec$/d
/^qdisc_qstats_cpu_qlen_dec$/d
/^qdisc_refcount_inc$/d
/^qdisc_root_sleeping_lock$/d
/^qh_destroy$/d
/^qtd_list_free$/d
/^queue_request_irq$/d
/^queue_set_hctx_shared$/d
/^queue_write$/d
/^quirk_pex_vca_alias$/d
/^quirk_poll_init$/d
/^ramoops_parse_dt_u32$/d
/^range_is_zero$/d
/^range_within$/d
/^rb_inc_iter$/d
/^rb_iter_reset$/d
/^rc_free_rx_device$/d
/^rcu_qs$/d
/^rcu_read_unlock_sched$/d
/^rcu_report_qs_rsp$/d
/^rdp_offload_toggle$/d
/^read_node_page$/d
/^record_times$/d
/^red_random$/d
/^ref_set_non_owning$/d
/^reg_btf_record$/d
/^reg_may_point_to_spin_lock$/d
/^register_memory_resource$/d
/^regs_exact$/d
/^regulator_ena_gpio_free$/d
/^regulator_unlock_two$/d
/^release_nodes$/d
/^release_pte_folio$/d
/^releaseintf$/d
/^relink_to_local$/d
/^remap_exception$/d
/^remove_boost_sysfs_file$/d
/^remove_breakpoint$/d
/^remove_full$/d
/^remove_hist_vars$/d
/^remove_hrtimer$/d
/^remove_partial$/d
/^remove_probe_files$/d
/^remove_tree$/d
/^removexattr$/d
/^replenish_dl_new_period$/d
/^reqsk_free$/d
/^reset_config$/d
/^reset_ctrl_pos$/d
/^rhashtable_lookup$/d
/^rhashtable_rehash_alloc$/d
/^rht_head_hashfn$/d
/^rht_lock$/d
/^rmap_walk_anon$/d
/^rmap_walk_file$/d
/^rpm_get_suppliers$/d
/^rproc_disable_iommu$/d
/^rt6_do_update_pmtu$/d
/^rt6_find_cached_rt$/d
/^rt_mutex_slowtrylock$/d
/^rtc_alarm_disable$/d
/^rtm_dump_nexthop_bucket_cb$/d
/^rtm_dump_walk_nexthops$/d
/^rtnl_af_lookup$/d
/^rtnl_dev_get$/d
/^rtnl_offload_xstats_get_stats$/d
/^rto_next_cpu$/d
/^rwsem_set_nonspinnable$/d
/^rwsem_write_trylock$/d
/^same_callsites$/d
/^sanitize_speculative_path$/d
/^save_register_state$/d
/^sb_start_write$/d
/^sbitmap_find_bit$/d
/^sbitmap_put$/d
/^scale64_check_overflow$/d
/^scale_down$/d
/^scale_up$/d
/^scanarg$/d
/^scarlett2_update_sync$/d
/^scarlett2_usb_get_config$/d
/^sch_tree_lock$/d
/^sch_tree_unlock$/d
/^sched_balance_newidle$/d
/^sched_set_rq_online$/d
/^scm_recv_unix$/d
/^scmi_create_protocol_devices$/d
/^scmi_event_handler_enable_events$/d
/^scmi_put_handler_unlocked$/d
/^scmi_vio_msg_release$/d
/^scmi_xfer_done_no_timeout$/d
/^scsi_handle_queue_ramp_up$/d
/^scsi_run_queue_async$/d
/^scsi_trace_misc$/d
/^scsi_try_target_reset$/d
/^sdev_format_header$/d
/^sdhci_check_ro$/d
/^sdhci_finish_mrq$/d
/^sdhci_set_adma_addr$/d
/^sdhci_set_card_detection$/d
/^sdhci_set_sdma_addr$/d
/^search_cmp_ftr_reg$/d
/^seccomp_assign_mode$/d
/^seccomp_notify_detach$/d
/^section_addr$/d
/^section_objs$/d
/^seg_info_from_raw_sit$/d
/^sel_make_inode$/d
/^sel_netif_find$/d
/^sel_remove_entries$/d
/^select_comparison_fn$/d
/^select_cpu_from_cluster$/d
/^send_reply$/d
/^seqiv_aead_encrypt_complete2$/d
/^serial8250_in_MCR$/d
/^serial8250_out_MCR$/d
/^serial_icr_read$/d
/^serio_disconnect_driver$/d
/^serio_reconnect_port$/d
/^serio_remove_pending_events$/d
/^set_abs$/d
/^set_badblock$/d
/^set_cleanup_entries$/d
/^set_fd_set$/d
/^set_ifa_lifetime$/d
/^set_info$/d
/^set_init_blocksize$/d
/^set_memory_rox$/d
/^set_mount_attributes$/d
/^set_pmd_at$/d
/^set_port_feature$/d
/^set_raw_inline$/d
/^set_thread_esr$/d
/^set_worker_dying$/d
/^setup_swap_info$/d
/^sg_miter_get_next_page$/d
/^sg_pool_free$/d
/^sha1_base_do_finalize$/d
/^sha256_base_do_finalize$/d
/^sha256_ce_transform$/d
/^shmem_get_partial_folio$/d
/^shmem_replace_entry$/d
/^shmem_vm_ops$/d
/^show_type$/d
/^shuffle_valid_page$/d
/^sigsuspend$/d
/^sk_memory_allocated_add$/d
/^sk_msg_free_elem$/d
/^sk_psock_put$/d
/^sk_psock_skb_ingress_self$/d
/^sk_psock_skb_state$/d
/^skb_advance_to_frag$/d
/^skb_clear_delivery_time$/d
/^skb_cow$/d
/^skb_ext_put$/d
/^skb_ext_put_sp$/d
/^skb_fill_page_desc$/d
/^skb_gro_postpull_rcsum$/d
/^skb_list_del_init$/d
/^skb_panic$/d
/^skb_postpull_rcsum$/d
/^skb_prepare_for_shift$/d
/^skb_put_zero$/d
/^skb_set_owner_r$/d
/^skb_setup_tx_timestamp$/d
/^skb_tunnel_info_txcheck$/d
/^slab_free_freelist_hook$/d
/^slab_pre_alloc_hook$/d
/^slim_stats_record$/d
/^snd_bbfpro_ctl_add$/d
/^snd_bbfpro_vol_add$/d
/^snd_ctl_get_ioff$/d
/^snd_ctl_new$/d
/^snd_djm_controls_create$/d
/^snd_ftu_create_effect_switch$/d
/^snd_hwdep_dsp_load$/d
/^snd_pcm_free_stream$/d
/^snd_pcm_start_lock_irq$/d
/^snd_power_unref$/d
/^snd_rawmidi_info_user$/d
/^snd_rawmidi_input_status$/d
/^snd_rawmidi_output_status$/d
/^snd_s1810c_switch_init$/d
/^snd_soc_add_controls$/d
/^snd_soc_del_component_unlocked$/d
/^snd_timer_find$/d
/^snd_timer_process_callbacks$/d
/^snd_timer_user_append_to_tqueue$/d
/^snd_timer_user_start$/d
/^snd_timer_user_status32$/d
/^snd_timer_user_status64$/d
/^snd_usb_cm106_write_int_reg$/d
/^snd_usb_find_input_terminal_descriptor$/d
/^snd_usb_find_output_terminal_descriptor$/d
/^snd_usbmidi_detect_per_port_endpoints$/d
/^snmp6_fill_stats$/d
/^snmp6_seq_show_item64$/d
/^snoop_urb$/d
/^soc_component_write_no_lock$/d
/^soc_dapm_connect_path$/d
/^soc_free_pcm_runtime$/d
/^soc_tplg_remove_widget$/d
/^sock_drop$/d
/^sock_hash_free_elem$/d
/^sock_lock_init\.__key$/d
/^sock_lock_init\.__key\.15$/d
/^sock_map_add_link$/d
/^sock_map_prog_update$/d
/^sock_recvmsg_nosec$/d
/^sock_rps_record_flow$/d
/^sony_set_leds$/d
/^space_used$/d
/^spectre_v4_mitigations_dynamic$/d
/^spectre_v4_mitigations_on$/d
/^spi_check_buswidth_req$/d
/^spi_destroy_queue$/d
/^spi_idle_runtime_pm$/d
/^spi_mem_access_end$/d
/^ssbd_prctl_enable_mitigation$/d
/^stage2_make_pte$/d
/^start_copy$/d
/^start_dir_add$/d
/^start_dl_timer$/d
/^start_in_transfer$/d
/^start_out_transfer$/d
/^start_poll_synchronize_rcu_common$/d
/^stat_put$/d
/^stats_put_ctrl_stats$/d
/^stats_put_mac_stats$/d
/^stats_put_phy_stats$/d
/^stats_put_rmon_stats$/d
/^stats_put_stats$/d
/^steam_do_connect_event$/d
/^stop_sustain_timers$/d
/^str_read$/d
/^stripe_map_range_sector$/d
/^strp_start_timer$/d
/^strstarts$/d
/^sub_rq_bw$/d
/^sub_running_bw$/d
/^submit_flush_wait$/d
/^sugov_kthread_stop$/d
/^sum_trb_lengths$/d
/^super_blocks$/d
/^super_lock$/d
/^support_inline_data$/d
/^supports_scale_freq_counters$/d
/^suspend_test$/d
/^sve_to_fpsimd$/d
/^swap_cgroup_ctrl$/d
/^swap_do_scheduled_discard$/d
/^swap_range_alloc$/d
/^swap_read_page$/d
/^swnode_graph_find_next_port$/d
/^sync_file_alloc\.__key$/d
/^sync_pending_stops$/d
/^synth_err$/d
/^sysctl_head_finish$/d
/^sysctl_head_grab$/d
/^task_contending$/d
/^task_fpsimd_load$/d
/^task_participate_group_stop$/d
/^task_sid_obj$/d
/^tcf_action_inc_overlimit_qstats$/d
/^tcf_action_offload_del_ex$/d
/^tcf_block_refcnt_get$/d
/^tcf_block_release$/d
/^tcf_block_unbind$/d
/^tcf_bpf_cfg_cleanup$/d
/^tcf_chain0_head_change$/d
/^tcf_chain_tp_find$/d
/^tcf_em_lookup$/d
/^tcf_exts_get_net$/d
/^tcf_proto_put$/d
/^tclass_notify$/d
/^tcp_add_reno_sack$/d
/^tcp_ca_find_autoload$/d
/^tcp_cleanup_skb$/d
/^tcp_ecn_check_ce$/d
/^tcp_inq$/d
/^tcp_measure_rcv_mss$/d
/^tcp_queue_rcv$/d
/^tcp_rcv_rtt_measure_ts$/d
/^tcp_sndbuf_expand$/d
/^tcp_try_keep_open$/d
/^tcp_try_to_open$/d
/^tcp_try_undo_dsack$/d
/^tcp_tsq_handler$/d
/^tcp_undo_cwnd_reduction$/d
/^tcp_update_skb_after_send$/d
/^tcpm_debugfs_exit$/d
/^tcpm_detach$/d
/^tcpm_enable_auto_vbus_discharge$/d
/^tcpm_get_current_limit$/d
/^tcpm_mux_set$/d
/^tcpm_pd_send_control$/d
/^tcpm_port_is_disconnected$/d
/^tcpm_queue_message$/d
/^tcpm_rp_cc$/d
/^tcpm_set_auto_vbus_discharge_threshold$/d
/^tcpm_set_charge$/d
/^tcpm_set_current_limit$/d
/^tcpm_set_partner_usb_comm_capable$/d
/^tcpm_set_polarity$/d
/^tcpm_set_pwr_role$/d
/^tcpm_set_state_cond$/d
/^tcpm_set_vbus$/d
/^tcpm_set_vconn$/d
/^tcpm_start_toggling$/d
/^tcpm_unregister_altmodes$/d
/^tegra186_bpmp_reset_channels$/d
/^tegra_pmc_clk_gate_register$/d
/^tegra_powergate_disable_clocks$/d
/^tegra_powergate_enable_clocks$/d
/^tegra_powergate_unprepare_clocks$/d
/^textify_hooks$/d
/^tfilter_notify$/d
/^tfilter_notify_chain$/d
/^tfilter_notify_prep$/d
/^tg_bps_limit$/d
/^tg_iops_limit$/d
/^thermal_of_zone_unregister$/d
/^thermal_set_governor$/d
/^thermal_zone_device_set_polling$/d
/^this_cpu_set_vectors$/d
/^thp_vma_allowable_orders$/d
/^thp_vma_suitable_orders$/d
/^tick_init_jiffy_update$/d
/^tick_nohz_activate$/d
/^time_state$/d
/^time_status$/d
/^timer_set_gparams$/d
/^timerfd_get_remaining$/d
/^to_current_namespace_index$/d
/^to_namespace_index$/d
/^total_mapping_size$/d
/^tpacket_get_timestamp$/d
/^trace_android_vh_page_cache_readahead_end$/d
/^trace_android_vh_page_cache_readahead_start$/d
/^trace_android_vh_shmem_mod_swapped$/d
/^trace_br_fdb_update$/d
/^trace_cgroup_setup_root$/d
/^trace_device_pm_callback_end$/d
/^trace_device_pm_callback_start$/d
/^trace_dwc3_complete_trb$/d
/^trace_event_probe_cleanup$/d
/^trace_event_put_ref$/d
/^trace_ext4_ext_convert_to_initialized_fastpath$/d
/^trace_ext4_fc_replay$/d
/^trace_f2fs_direct_IO_enter$/d
/^trace_f2fs_direct_IO_exit$/d
/^trace_f2fs_do_write_data_page$/d
/^trace_f2fs_fiemap$/d
/^trace_f2fs_issue_reset_zone$/d
/^trace_generic_delete_lease$/d
/^trace_hmbird_fatal_info$/d
/^trace_ma_op$/d
/^trace_mm_collapse_huge_page_isolate$/d
/^trace_mm_filemap_delete_from_page_cache$/d
/^trace_page_pool_state_hold$/d
/^trace_rcu_utilization$/d
/^trace_rpm_return_int$/d
/^trace_rtc_timer_dequeue$/d
/^trace_rtc_timer_enqueue$/d
/^trace_save_cmdline$/d
/^trace_scmi_fc_call$/d
/^trace_spi_controller_idle$/d
/^trace_suspend_resume$/d
/^trace_ufshcd_profile_clk_scaling$/d
/^trace_writeback_pages_written$/d
/^trace_xdp_exception$/d
/^trace_xdp_redirect_err$/d
/^trace_xhci_address_ctx$/d
/^tracing_map_free_elts$/d
/^tracing_stop_tr$/d
/^track_chunk$/d
/^track_data_free$/d
/^traverse_mounts$/d
/^truncate_folio_batch_exceptionals$/d
/^try_to_unmap_one$/d
/^ttm_bo_get$/d
/^ttm_pool_debugfs_orders$/d
/^ttm_pool_type_take$/d
/^ttwu_queue_wakelist$/d
/^tty_ldisc_close$/d
/^tty_ldisc_failto$/d
/^tty_ldisc_get$/d
/^tty_ldisc_kill$/d
/^tty_ldisc_open$/d
/^tty_ldisc_put$/d
/^tty_set_serial$/d
/^tty_set_termios_ldisc$/d
/^tty_update_time$/d
/^tun_detach_filter$/d
/^tun_flow_uninit$/d
/^tun_get_iff$/d
/^tun_set_ebpf$/d
/^txopt_put$/d
/^u32_clear_hw_hnode$/d
/^u32_destroy_key$/d
/^u32_reoffload_hnode$/d
/^u32_unbind_filter$/d
/^uac_mixer_unit_get_channels$/d
/^uart_console_registered$/d
/^uas_free_streams$/d
/^uas_try_complete$/d
/^uas_xfer_data$/d
/^uas_zap_pending$/d
/^ublk_free_dev_number$/d
/^ublk_idr_freed$/d
/^ublk_queue_cmd$/d
/^ublk_remove$/d
/^uclamp_rq_dec_id$/d
/^uclamp_rq_inc_id$/d
/^uclogic_params_frame_init_with_desc$/d
/^uclogic_params_get_str_desc$/d
/^uclogic_params_init_with_opt_desc$/d
/^uclogic_params_ugee_v2_has_battery$/d
/^uclogic_probe_interface$/d
/^ucsi_next_altmode$/d
/^ucsi_read_pdos$/d
/^ucsi_register_partner$/d
/^ucsi_role_cmd$/d
/^udp4_csum_init$/d
/^udp_tunnel_get_rx_info$/d
/^ufshcd_add_command_trace$/d
/^ufshcd_dme_peer_set$/d
/^ufshcd_dme_set$/d
/^ufshcd_hba_vreg_set_lpm$/d
/^ufshcd_host_memory_configure$/d
/^ufshcd_print_evt$/d
/^ufshcd_read_unit_desc_param$/d
/^ufshcd_set_req_abort_skip$/d
/^ufshcd_update_ee_drv_mask$/d
/^uhid_dev_destroy$/d
/^uhid_queue_event$/d
/^uhid_report_wake_up$/d
/^uinput_validate_absinfo$/d
/^uio_major_cleanup$/d
/^umount_mnt$/d
/^umount_one$/d
/^unbind_marked_interfaces$/d
/^unblock_operations$/d
/^uncharge_batch$/d
/^uncharge_folio$/d
/^unix_create1\.__key\.22$/d
/^unix_table_double_lock$/d
/^unix_table_double_unlock$/d
/^unlink_obj$/d
/^unlock_mount$/d
/^unmap_mapping_range_tree$/d
/^unnote_qf_name$/d
/^unroll_tree_refs$/d
/^unset_regulator_supplies$/d
/^update_cfs_rq_load_avg$/d
/^update_dind_extent_range$/d
/^update_dl_migration$/d
/^update_extent_range$/d
/^update_fs_metadata$/d
/^update_history$/d
/^update_ind_extent_range$/d
/^update_inode_attr$/d
/^update_partition_sd_lb$/d
/^update_rt_migration$/d
/^update_rx_stats$/d
/^usb_deregister_bus$/d
/^usb_disable_remote_wakeup$/d
/^usb_put_invalidate_rhdev$/d
/^usb_set_device_initiated_lpm$/d
/^usb_set_lpm_timeout$/d
/^usb_stop_hcd$/d
/^usbfs_decrease_memory_usage$/d
/^usbfs_increase_memory_usage$/d
/^usbfs_start_wait_urb$/d
/^user_regset_copyin$/d
/^userfaultfd_event_wait_completion$/d
/^uuid_equal$/d
/^uvc_alloc_chain$/d
/^uvc_ctrl_send_event$/d
/^uvc_ctrl_send_slave_event$/d
/^uvc_get_ctrl_bitmap$/d
/^uvc_query_name$/d
/^uvc_v4l2_get_format$/d
/^uvc_video_free_request$/d
/^valid_inferred_mode$/d
/^vb2_warn_zero_bytesused$/d
/^verify_one_alg$/d
/^verify_reserved_gdb$/d
/^verify_sec_ctx_len$/d
/^verity_verify_level$/d
/^verity_verify_pending_blocks$/d
/^veth_disable_xdp_range$/d
/^veth_init_queues$/d
/^veth_set_xdp_features$/d
/^veth_xdp_tx$/d
/^vfat_find_form$/d
/^vfat_update_dir_metadata$/d
/^vfat_update_dotdot_de$/d
/^vfs_cleanup_quota_inode$/d
/^vgic_get_irq_kref$/d
/^vgic_its_alloc_collection$/d
/^vgic_its_alloc_ite$/d
/^vgic_its_free_device$/d
/^vhost_get_vq_from_user$/d
/^vhost_vsock_get$/d
/^vhost_worker_destroy$/d
/^virtio_fs_start_all_queues$/d
/^virtio_net_hdr_set_proto$/d
/^visit_func_call_insn$/d
/^vm_area_cachep$/d
/^vm_flags_clear$/d
/^vma_lock_alloc\.__key$/d
/^vma_lock_cachep$/d
/^vmap_area_root$/d
/^vmf_pte_changed$/d
/^vq_log_used_access_ok$/d
/^vring_alloc_state_extra_packed$/d
/^vring_alloc_state_extra_split$/d
/^vring_create_virtqueue_split$/d
/^vring_free_split$/d
/^vsock_auto_bind$/d
/^vsock_dequeue_accept$/d
/^vsock_update_buffer_size$/d
/^vti6_update$/d
/^wacom_intuos_bt_process_data$/d
/^wacom_leds_alloc_and_register$/d
/^wacom_notify_battery$/d
/^wacom_report_numbered_buttons$/d
/^wacom_s32tou$/d
/^wacom_set_barrel_switch3_usage$/d
/^wacom_tpc_single_touch$/d
/^wacom_wac_finger_count_touches$/d
/^wait_for_xmitr$/d
/^wait_transaction_locked$/d
/^wakeup_pipe_readers$/d
/^wakeup_source_deactivate$/d
/^wakeup_source_report_event$/d
/^walk_component$/d
/^watchdog_ping$/d
/^watchdog_update_worker$/d
/^wb_put$/d
/^wbt_update_limits$/d
/^wext_ioctl_dispatch$/d
/^wg_peer_get$/d
/^wg_queue_enqueue_per_peer_rx$/d
/^wg_queue_enqueue_per_peer_tx$/d
/^wiimote_cmd_init_ext$/d
/^wiimote_mp_load$/d
/^work_exited$/d
/^write_header$/d
/^xa_cmpxchg$/d
/^xas_start$/d
/^xdp_umem_unaccount_pages$/d
/^xdp_umem_unpin_pages$/d
/^xdp_update_frame_from_buff$/d
/^xfrm_fill_dst$/d
/^xfrm_flowi_sport$/d
/^xfrm_mark_get$/d
/^xfrm_nlmsg_multicast$/d
/^xfrm_offload$/d
/^xfrm_pol_hold$/d
/^xfrm_policy_find_inexact_candidates$/d
/^xfrm_pols_put$/d
/^xfrm_secpath_reject$/d
/^xfrm_state_find\.saddr_wildcard$/d
/^xfrm_state_hold$/d
/^xfrm_state_look_at$/d
/^xfrm_state_netlink$/d
/^xfrm_state_put$/d
/^xfrm_states_delete$/d
/^xfrm_states_put$/d
/^xhci_check_usb2_port_capability$/d
/^xhci_create_rhub_port_array$/d
/^xhci_debugfs_extcap_regset$/d
/^xhci_find_next_ext_cap$/d
/^xhci_free_host_resources$/d
/^xhci_get_hw_deq$/d
/^xhci_get_timeout_no_hub_lpm$/d
/^xhci_get_virt_ep$/d
/^xhci_handle_stopped_cmd_ring$/d
/^xhci_hcd_init_usb3_data$/d
/^xhci_set_port_power$/d
/^xhci_trb_type_string$/d
/^xhci_virt_ep_to_ring$/d
/^xp_disable_drv_zc$/d
/^xpad360w_start_input$/d
/^xpad_deinit_output$/d
/^xpad_try_sending_next_out_packet$/d
/^xsk_consume_skb$/d
/^xsk_init_queue$/d
/^xsk_map_sock_delete$/d
/^xsk_unbind_dev$/d
/^xts_cts_final$/d
/^zext_32_to_64$/d
/^zone_watermark_fast$/d
